apiVersion: apps/v1

kind: Deployment

metadata:

  name: hello

  namespace: lasample

  labels:

    app: hello
replicas: 5
spec:

  selector:

    matchLabels:

      app: hello

  template:

    metadata:

      labels:

        app: hello

    spec:

      containers:

      - name: hello

        image: acgtes/gitops:hellov1.1
